config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :questions do
    # Use member since want :id, not :question_id, in routes
    # http://stackoverflow.com/questions/5182734/what-does-a-member-and-collection-route-mean
    # Good examples in original routes file (as comments)
   member do
      post 'upvote'
      post 'downvote'
      get :autocomplete
    end
    resources :answers, only: [:create, :edit, :update, :destroy] do
      member do
        post 'upvote'
        post 'downvote'
        get :autocomplete
      end
    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  searchkick autocomplete: ['title']
  belongs_to :question

  validates :title, :content, presence: true, length: {minimum: 6}
  validates :title, uniqueness: true

  validates :vote_count, numericality: {greater_than_or_equal_to: 0}

  def upvote
    update_attributes(vote_count: vote_count + 1)
  end

  def downvote
    update_attributes(vote_count: vote_count - 1)
  end
end

app/models/concerns/zen_quote.rb
module ZenQuote
  extend ActiveSupport::Concern

  def get_quote
    url = 'https://api.github.com/zen'
    response = HTTParty.get(url)
    if response.code == 403 || response.code == 401
      return_string = 'Unfortunately, Github has rate limited us'
    else
      return_string = response
    end
    return_string
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  searchkick autocomplete: ['title']
  has_many :answers, dependent: :destroy

  validates :title, :content, presence: true, length: { minimum: 6 }
  validates :title, uniqueness: true

  validates :vote_count, numericality: {greater_than_or_equal_to: 0}

  def upvote
    update_attributes(vote_count: vote_count + 1)
  end

  def downvote
    update_attributes(vote_count: vote_count - 1)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(params_answer)
    @answer.save
    redirect_to question_path(@question)
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.update(params_answer)
    redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(params[:question_id])
    Answer.find(params[:id]).destroy
    redirect_to question_path(@question)
  end

  def upvote
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.upvote
    redirect_to question_path(@question)
  end

  def downvote
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.downvote
    redirect_to question_path(@question)
  end

  def autocomplete
    render json: Answer.search(params[:query], autocomplete: true, limit: 10).map(&:title)
  end

  private

  def params_answer
    params.require(:answer).permit(:title, :content, :vote_count)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include ZenQuote
  def index
    @quote = get_quote
    if params[:query].present?
      @questions = Question.search(params[:query], page: params[:page])
    else
      @questions = Question.order('created_at DESC')
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order('created_at DESC')
  end

  def create
    @question = Question.new(params_question)
    # @error = @question.errors.full_messages.to_sentence
    respond_to do |format|
      if @question.save
        format.html {redirect_to question_path(@question)}
        format.json {render json: @question}
      else
        format.html {render 'index'}
        format.json {render json: @error, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @question = Question.find(params[:id])

  end

  def update
    @question = Question.find(params[:id])
    @question.update(params_question)
    redirect_to question_path(@question)
  end

  def destroy
    Question.find(params[:id]).destroy
    redirect_to questions_path
  end

  def upvote
    @question = Question.find(params[:id])
    respond_to do |format|
      if @question.upvote
        format.html {redirect_to questions_path}
        format.json {render json: @question}
      else
        format.html {render 'index'}
        format.json {render json: @errors}
      end
    end
  end

  def downvote
    @question = Question.find(params[:id])
    respond_to do |format|
      if @question.downvote
        format.html {redirect_to questions_path}
        format.json {render json: @question}
      else
        format.html {render 'index'}
        format.json {render json: @errors}
      end
    end
  end

  def autocomplete
    render json: Question.search(params[:query], autocomplete: true, limit: 10).map(&:title)
  end

  private

  def params_question
    params.require(:question).permit(:title, :content, :vote_count)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.erb
<%= form_for :answer, method: method, url: url do |f| %>
<%= f.label "Title" %>
<%= f.text_area :title %>
<%= f.label "Content" %>
<%= f.text_area :content %>
<%= f.submit %>
<% end %>

app/views/answers/edit.html.erb
<h1> Edit your Answer here </h1>
<div>
  <%= render partial: 'form', locals: {method: 'patch', url: question_answer_path(@answer.question, @answer)} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflow Clone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row container-fluid header">
  <div class="col-md-2">logo here</div>
  <div class="col-md-1">spacer</div>
  <div class="col-md-2">tabs here</div>
  <div class="col-md-2">tabs here</div>
  <div class="col-md-2">tabs here</div>
  <div class="col-md-3">search bar</div>
</div>

<div class="row container-fluid">
  <div class="col-md-2">logo goes here</div>
  <div class="col-md-8"><h1>Welcome to a StackOverflow Clone</h1></div>
  <div class="col-md-2 pad-20"><%=link_to "Home", root_path %></div>
</div>

  <%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<div class="container error" id="errors">
  <% if @error %>
  <%= @error %>
  <% end %>
</div>
<div class="row container-fluid">
  <%= form_for :question, url: url, method: method do |f| %>
  <div class="col-md-6">
    <%= f.label "Title" %>
    <%= f.text_area :title %>
  </div>
  <div class="col-md-6">
    <%= f.label "Content" %>
    <%= f.text_area :content %>
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<h1> Edit your Question here </h1>
<div>
  <%= render partial: 'form',  locals: {url: question_path(@question), method: :patch} %>
</div>

app/views/questions/index.html.erb
<h1>Stack Overflow Clone</h1>
<div class="row container-fluid">
  <h3>Quote of the day: <%= @quote %></h3>
</div>
<div class="row container-fluid">
  <%= form_tag questions_path, class: "form-inline", method: :get do %>
  <div class="input-group input-group-lg col-med-12">
    <% if params[:query].present? %>
    <div class="input-group-btn">
      <%= link_to "clear", questions_path, class: "btn btn-default" %>
    </div>
    <% end %>
    <%= text_field_tag :query, params[:query], class: "form-control", id: "question_search", autocomplete: "off" %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  </div>
  <% end %>
</div>
<div class="row container-fluid">
  <div class="col-med-12">
    <h2>New Question</h2>
  </div>
</div>
<div class="row container-fluid" id="new_Q">
  <%= render partial: 'form' ,  locals: {url: questions_path, method: :post}%>
</div>
<div class="row container-fluid" id="questions_box">
  <h2>Existing Questions</h2>
  <% @questions.each do |question|%>
</div>
<div class="row container-fluid" id="id_<%= question.id %>">
  <div class="col-md-10">
    <div class="col-md-2 vote_count">
      <span>
        <%= question.vote_count %>
      </span>
      <%= button_to '+', upvote_question_path(question) %>
      <%= button_to '-', downvote_question_path(question) %>
    </div>
    <div class="col-md-8">
      <%= link_to "#{question.title} )", question_path(question)%>
    </div>
  </div>
  <div class="col-md-2">
    <%= link_to 'Edit', edit_question_path(question) %>,
    <%= link_to 'Delete', question_path(question), method: :delete, data: { confirm: 'You sure?' } %>
  </div>
  <% end %>
</div>
<!-- Handlebars script -->
<script id="new-question-form" type="text/x-handlebars-template">
<div class="row container-fluid" id="id_{{id}}">
  <div class="col-md-10">
    <div class="col-md-2 vote_count">
      <span>
        Votes: {{vote_count}}
      </span>
      <form class="button_to" method="post" action="/questions/{{id}}/upvote">
        <input type="submit" value="Upvote">
      </form>
      <form class="button_to" method="post" action="/questions/{{id}}/downvote">
        <input type="submit" value="Downvote">
      </form>
    </div>
    <div class="col-md-8">
      <a href="/questions/{{id}}">{{title}}</a>
    </div>
  </div>
</div>
</script>

app/views/questions/new.html.erb
You can create a new question on the main page.

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<h3><%= @question.content %></h2>

<h2>New Answer</h2>
<%= render partial: 'answers/form', locals: {method: 'post', url: question_answers_path(@question)}%>
<h2>Existing Answers</h2>
<ul>
  <% @answers.each do |answer| %>
  <div>
  <li>
    <%= "#{answer.title} (#{answer.vote_count})" %>
    <%= button_to '+', upvote_question_answer_path(@question, answer) %>
    <%= button_to '-', downvote_question_answer_path(@question, answer) %>
    <%= link_to 'Edit', edit_question_answer_path(@question,answer) %>,
     <%= link_to 'Delete', question_answer_path(answer.question, answer), method: :delete%>
  </li>
  </div>
  <% end %>
</ul>